version: "2"

services:
  archivefs:
    image: "local/invest-fileserver:latest"
    ports:
      - "3001:3001"
    volumes:
     - "/invest/archive/:/fileshare/:z"
    restart: "always"

#  redis:
#    image: "redis:3.2.6-alpine"
#    volumes:
#     - "/invest/redis/:/data/:z"
#    restart: "always"
#    command: "redis-server --appendonly yes"

#  postgres:
#    image: "postgres:9.6"
#    container_name: "postgres"
#    ports:
#     - "5432:5432"
#    volumes:
#     - "/invest/postgres/data:/var/lib/postgresql/data:z"
#    restart: "always"

  wordpress:
    image: wordpress
    container_name: "wordpress"
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
     - "/invest/wordpress:/var/www/html/wp-content:z"

  mysql:
    image: mariadb
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /invest/mysql:/var/lib/mysql:z

  imacros:
    image: "ptang83/firefox-imacros:latest"
#    image: selenium/standalone-firefox-debug
    container_name: "imacros"
    shm_size: 300m 
    volumes:
     - "/invest/imacros/Macros:/home/seluser/iMacros/Macros:z"
     - "/invest/imacros/Downloads:/home/seluser/iMacros/Downloads:z"
    ports:
     - "4444:4444"
     - "5901:5900"
    restart: "always"

#  nexus:
#    image: sonatype/nexus 
#    container_name: "nexus"
#    ports:
#      - 8081:8081
#    volumes:
#      - /invest/nexus-data:/nexus-data:z
