version: "2"

services:
  archivefs:
    image: "local/invest-fileserver:latest"
    ports:
      - "3001:3001"
    volumes:
     - "/invest/archive/:/fileshare/:z"
    restart: "always"

  redis:
    image: "redis:3.2.6-alpine"
    volumes:
     - "/invest/redis/:/data/:z"
    restart: "always"
    command: "redis-server --appendonly yes"

  postgres:
    image: "postgres:9.6"
    container_name: "postgres"
    ports:
     - "5432:5432"
    volumes:
     - "/invest/postgres/data:/var/lib/postgresql/data:z"
    restart: "always"

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /invest/mysql:/var/lib/mysql
